from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false

pre_bump_hooks = [
  "uv version {{version}}",
  "bun pm version {{version}} --no-git-tag-version"
]

post_bump_hooks = [
  "git push origin main",
  "git push origin {{version}}"
]
pre_package_bump_hooks = [
  "echo {{version}} > .version"
]
post_package_bump_hooks = [
  "git push origin main",
  "git push origin {{package}}-{{version}}"
]

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "3cikl"
repository = "3cikl.meta"
authors = [
  {username = "3cikl", signature = "3cikl"}
]

[bump_profiles]

[monorepo.packages]
